'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1022
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("IT193_Unit8_JasonChapell.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Afghanistan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afghanistan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Albania() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Albania", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Algeria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Algeria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property American_Samoa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("American_Samoa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Andorra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Andorra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Angola() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Angola", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Anguilla() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anguilla", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Antigua_and_Barbuda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Antigua_and_Barbuda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Argentina() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Argentina", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Armenia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Armenia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Aruba() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aruba", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Australia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Australia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Austria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Austria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Azerbaijan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Azerbaijan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bahamas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bahamas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bahrain() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bahrain", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bangladesh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bangladesh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Barbados() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Barbados", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Belarus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Belarus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Belgium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Belgium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Belize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Belize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Benin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Benin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bermuda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bermuda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bhutan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bhutan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bolivia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bolivia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bosnia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bosnia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Botswana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Botswana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Brazil() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Brazil", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property British_Virgin_Islands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("British_Virgin_Islands", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Brunei() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Brunei", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bulgaria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bulgaria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Burkina_Faso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Burkina_Faso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Burundi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Burundi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cambodia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cambodia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cameroon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cameroon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Canada() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Canada", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cape_Verde() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cape_Verde", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cayman_Islands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cayman_Islands", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Central_African_Republic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Central_African_Republic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Chad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Chile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property China() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("China", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Christmas_Island() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Christmas_Island", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Colombia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Colombia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comoros() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comoros", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cook_Islands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cook_Islands", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Costa_Rica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Costa_Rica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Côte_d_Ivoire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Côte_d_Ivoire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Croatia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Croatia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cuba() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cuba", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cyprus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cyprus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Czech_Republic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Czech_Republic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Democratic_Republic_of_the_Congo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Democratic_Republic_of_the_Congo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Denmark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Denmark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Djibouti() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Djibouti", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dominica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dominica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dominican_Republic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dominican_Republic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ecuador() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ecuador", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Egypt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Egypt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property El_Salvador() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("El_Salvador", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Equatorial_Guinea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Equatorial_Guinea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Eritrea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Eritrea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Estonia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Estonia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ethiopia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ethiopia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Falkland_Islands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Falkland_Islands", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Faroe_Islands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Faroe_Islands", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fiji() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fiji", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Finland() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Finland", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property France() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("France", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property French_Polynesia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("French_Polynesia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gabon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gabon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gambia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gambia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Georgia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Georgia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Germany() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Germany", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ghana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ghana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gibraltar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gibraltar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Greece() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Greece", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Greenland() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Greenland", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Grenada() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grenada", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Guam() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Guam", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Guatemala() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Guatemala", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Guinea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Guinea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Guinea_Bissau() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Guinea_Bissau", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Guyana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Guyana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Haiti() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Haiti", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Honduras() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Honduras", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hong_Kong() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hong_Kong", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hungary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hungary", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Iceland() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Iceland", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property India() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("India", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Indonesia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Indonesia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Iran() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Iran", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Iraq() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Iraq", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ireland() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ireland", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Israel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Israel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Italy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Italy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Jamaica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jamaica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Japan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Japan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Jordan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jordan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kazakhstan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kazakhstan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kenya() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kenya", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kiribati() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kiribati", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kuwait() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kuwait", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kyrgyzstan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kyrgyzstan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Laos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Laos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Latvia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Latvia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lebanon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lebanon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lesotho() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lesotho", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Liberia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Liberia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Libya() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Libya", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Liechtenstein() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Liechtenstein", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lithuania() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lithuania", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Luxembourg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Luxembourg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Macao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Macao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Macedonia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Macedonia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Madagascar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Madagascar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Malawi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Malawi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Malaysia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Malaysia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Maldives() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maldives", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mali() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mali", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Malta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Malta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Marshall_Islands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Marshall_Islands", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Martinique() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Martinique", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mauritania() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mauritania", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mauritius() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mauritius", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mexico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mexico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Micronesia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Micronesia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Moldova() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Moldova", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Monaco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Monaco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mongolia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mongolia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Montserrat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Montserrat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Morocco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Morocco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mozambique() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mozambique", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Myanmar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Myanmar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Namibia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Namibia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nauru() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nauru", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nepal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nepal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Netherlands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Netherlands", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Netherlands_Antilles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Netherlands_Antilles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property New_Zealand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New_Zealand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nicaragua() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nicaragua", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Niger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Niger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nigeria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nigeria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Niue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Niue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Norfolk_Island() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Norfolk_Island", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property North_Korea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("North_Korea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Norway() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Norway", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Oman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Oman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pakistan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pakistan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Palau() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Palau", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Panama() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Panama", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Papua_New_Guinea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Papua_New_Guinea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Paraguay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paraguay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Peru() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Peru", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Philippines() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Philippines", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pitcairn_Islands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pitcairn_Islands", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Poland() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Poland", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Portugal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Portugal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Puerto_Rico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Puerto_Rico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Qatar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Qatar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Republic_of_the_Congo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Republic_of_the_Congo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Romania() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Romania", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Russian_Federation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Russian_Federation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rwanda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rwanda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Saint_Kitts_and_Nevis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Saint_Kitts_and_Nevis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Saint_Lucia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Saint_Lucia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Saint_Pierre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Saint_Pierre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Saint_Vicent_and_the_Grenadines() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Saint_Vicent_and_the_Grenadines", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Samoa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Samoa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property San_Marino() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("San_Marino", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sao_Tomé_and_Príncipe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sao_Tomé_and_Príncipe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Saudi_Arabia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Saudi_Arabia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Senegal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Senegal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Serbia_and_Montenegro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Serbia_and_Montenegro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Seychelles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Seychelles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sierra_Leone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sierra_Leone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Singapore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Singapore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Slovakia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Slovakia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Slovenia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Slovenia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Soloman_Islands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Soloman_Islands", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Somalia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Somalia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property South_Africa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("South_Africa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property South_Georgia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("South_Georgia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property South_Korea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("South_Korea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Soviet_Union() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Soviet_Union", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Spain() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spain", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sri_Lanka() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sri_Lanka", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sudan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sudan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Suriname() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Suriname", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Swaziland() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Swaziland", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sweden() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sweden", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Switzerland() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Switzerland", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Syria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Syria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Taiwan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Taiwan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tajikistan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tajikistan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tanzania() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tanzania", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Thailand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thailand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tibet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tibet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Timor_Leste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Timor_Leste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Togo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Togo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tonga() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tonga", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Trinidad_and_Tobago() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trinidad_and_Tobago", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tunisia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tunisia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Turkey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Turkey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Turkmenistan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Turkmenistan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Turks_and_Caicos_Islands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Turks_and_Caicos_Islands", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tuvalu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tuvalu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UAE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UAE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Uganda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uganda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ukraine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ukraine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property United_Kingdom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("United_Kingdom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property United_States_of_America() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("United_States_of_America", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Uruguay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uruguay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property US_Virgin_Islands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("US_Virgin_Islands", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Uzbekistan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uzbekistan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vanuatu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vanuatu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vatican_City() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vatican_City", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Venezuela() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Venezuela", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vietnam() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vietnam", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Wallis_and_Futuna() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wallis_and_Futuna", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Yemen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Yemen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Zambia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zambia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Zimbabwe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zimbabwe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
